modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Bede16/WildPaths/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/Bede16/WildPaths"
authors="Bede16"
description='''
Creates and recovers natural paths from player traffic, tramples vegetation, and ages exposed blocks through configurable transitions.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="yet_another_config_lib_v3"
type="required"
versionRange="[3.8.2,)"
ordering="NONE"
side="CLIENT"

